--
-- QUAIS AS TABELAS QUE NÃO CONTEM NENHUM INDICE
--
SELECT * FROM (SELECT A.TABLE_NAME, 
 NVL((SELECT COUNT(*)  
    FROM DBA_INDEXES X  WHERE X.OWNER='NETFORCE' AND A.OWNER = X.OWNER AND A.TABLE_NAME = X.TABLE_NAME
   GROUP BY X.TABLE_NAME),0) QTDIND
FROM DBA_TABLES A  WHERE A.OWNER='NETFORCE')  WHERE QTDIND =0 ORDER BY TABLE_NAME

--
-- QUAIS AS FKS DE RERENCIA QUE EXISTE NO SISTEMA
--
SELECT a.TABLE_NAME, B.COLUMN_NAME, B.POSITION FROM DBA_CONSTRAINTS a, DBA_CONS_COLUMNS b
 WHERE a.OWNER ='NETFORCE' AND a.CONSTRAINT_TYPE ='R' AND
       b.owner ='NETFORCE' AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME

--
-- VERIFICA QUAIS FK QUE NAO CONTEM UM INDICE PARA A REFERENCIA DA CONSULTA 
--
SELECT a.TABLE_NAME, B.COLUMN_NAME, B.POSITION FROM DBA_CONSTRAINTS a, DBA_CONS_COLUMNS b
 WHERE a.OWNER ='NETFORCE' AND a.CONSTRAINT_TYPE ='R' AND
       b.owner ='NETFORCE' AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME AND 
       (SELECT COUNT(*) FROM DUAL WHERE EXISTS
       (SELECT NULL FROM DBA_INDEXES X, DBA_IND_COLUMNS Y
WHERE X.OWNER='NETFORCE' AND X.TABLE_NAME =A.TABLE_NAME AND 
      Y.INDEX_OWNER='NETFORCE' AND Y.TABLE_NAME = X.TABLE_NAME )) = 0