---PROCESSO 021
MATRICES
MATRIZ_BLOQUEO
TOTALES_POR_RUBRO_NIVEL_HIST
RUBROS_NO_INCLUIDOS_MATRIZ
MOVTOS_PROMOCIONES_ISSR
SALDOS_BONUS
VALPAR_EMI_PROD_GROUP
VALPAR_EMI_PROD
ESTADOS_CTAS_TARJ
TARJETAS
NIV_FACT_TARJ_EMP
SALDOS_CUENTAS_NIVEL
CIERRES
RUBROS_NO_INCLUIDOS_MATRIZ
CUENTAS
MATRIZ_ACC_CTAS
MENSAJES_MATRIZ
CLEARING_ACCOUNTS
VALPAR_EMI_PRO_TAR
SALDOS_CUENTAS
TIPOS_DOCUMENTOS
VINCULADOS
PERSONAS
EMPRESAS
WFQ_QUEUE
CUENTAS_EXCEPCIONES_MATRIZ
MONEDAS_EMISORES_PRODUCTOS
MONEDAS
UNPAID_MOVEMENTS
TIPO_DE_CAMBIO
PAYMENTS_ASSIGNATION
CALENDARIO_CIERRES
MONEDAS_EMISORES_PRODUCTOS
COMPANY_LEVELS_TOTALS
ACCOUNT_DELAY
CUENTAS_COMPLEMENTARIO
ACCOUNT_INSURANCE
CARDS_PLASTIC_HISTORY
FECHAS_ESTADO_CTAS
ACCIONES_EXC_FILE
FECHAS_ESTADO_TARJETAS
EXCEPTION_ACC_CARDS
TRANSICION_ESTADOS



br_crdu_dba_analyze_brsassmm085_00003_s_c
                                                          
                                             
ANALYZE TABLE AUTO_MASTER_CB               DELETE STATISTICS;
ANALYZE TABLE CIERRES                      DELETE STATISTICS;
ANALYZE TABLE CONV_VISA_EUROPAY            DELETE STATISTICS;
ANALYZE TABLE CTF_AUTO_GENERADOS_ISSR      DELETE STATISTICS;
ANALYZE TABLE CTF_GENERADOS_ISSR           DELETE STATISTICS;
ANALYZE TABLE CUENTAS                      DELETE STATISTICS;
ANALYZE TABLE DAILY_INTERESTS_INFORM       DELETE STATISTICS;
ANALYZE TABLE ESTADOS_CTAS_TARJ            DELETE STATISTICS;
ANALYZE TABLE GENERAL_LEDGER_CONTROL       DELETE STATISTICS;
ANALYZE TABLE GL_CONTROL_TB                DELETE STATISTICS;
ANALYZE TABLE ISSUER_GENERAL_LEDGER        DELETE STATISTICS;
ANALYZE TABLE MANUAL_GENERAL_LEDGER        DELETE STATISTICS;
ANALYZE TABLE MANUAL_LEDGER_CONTROL        DELETE STATISTICS;
ANALYZE TABLE MASTER_CHARGE_BACK           DELETE STATISTICS;
ANALYZE TABLE MONEDAS_EMISORES_PRODUCTOS   DELETE STATISTICS;
ANALYZE TABLE MOVTOS_CUENTAS               DELETE STATISTICS;
ANALYZE TABLE PERDIDAS_EMISOR              DELETE STATISTICS;
ANALYZE TABLE PRODUCTOS                    DELETE STATISTICS;
ANALYZE TABLE REPROCESS_TXNS               DELETE STATISTICS;
ANALYZE TABLE RUBROS                       DELETE STATISTICS;
ANALYZE TABLE SALDOS_CUENTAS               DELETE STATISTICS;
ANALYZE TABLE SELLOS                       DELETE STATISTICS;
ANALYZE TABLE TARJETAS                     DELETE STATISTICS;
ANALYZE TABLE TRANS_BATCH_ISSR             DELETE STATISTICS;
ANALYZE TABLE TRANSFER_TRANS               DELETE STATISTICS;
ANALYZE TABLE WFQ_INFO_ADICIONAL           DELETE STATISTICS;
ANALYZE TABLE WFQ_MENSAJES                 DELETE STATISTICS;
ANALYZE TABLE WFQ_HIST_ESTADOS             DELETE STATISTICS;
ANALYZE TABLE FECHAS_ESTADO_TARJETAS       DELETE STATISTICS;
ANALYZE TABLE TIPO_DE_CAMBIO               DELETE STATISTICS;
ANALYZE TABLE S_ENTIDAD_SERV               DELETE STATISTICS;
--
ANALYZE TABLE AUTO_MASTER_CB               COMPUTE STATISTICS;
ANALYZE TABLE CIERRES                      COMPUTE STATISTICS;
ANALYZE TABLE CONV_VISA_EUROPAY            COMPUTE STATISTICS;
ANALYZE TABLE CTF_AUTO_GENERADOS_ISSR      COMPUTE STATISTICS;
ANALYZE TABLE CTF_GENERADOS_ISSR           COMPUTE STATISTICS;
ANALYZE TABLE CUENTAS                      COMPUTE STATISTICS;
ANALYZE TABLE DAILY_INTERESTS_INFORM       COMPUTE STATISTICS;
ANALYZE TABLE ESTADOS_CTAS_TARJ            COMPUTE STATISTICS;
ANALYZE TABLE GENERAL_LEDGER_CONTROL       COMPUTE STATISTICS;
ANALYZE TABLE GL_CONTROL_TB                COMPUTE STATISTICS;
ANALYZE TABLE ISSUER_GENERAL_LEDGER        COMPUTE STATISTICS;
ANALYZE TABLE MANUAL_GENERAL_LEDGER        COMPUTE STATISTICS;
ANALYZE TABLE MANUAL_LEDGER_CONTROL        COMPUTE STATISTICS;
ANALYZE TABLE MASTER_CHARGE_BACK           COMPUTE STATISTICS;
ANALYZE TABLE MONEDAS_EMISORES_PRODUCTOS   COMPUTE STATISTICS;
ANALYZE TABLE MOVTOS_CUENTAS               COMPUTE STATISTICS;
ANALYZE TABLE PERDIDAS_EMISOR              COMPUTE STATISTICS;
ANALYZE TABLE PRODUCTOS                    COMPUTE STATISTICS;
ANALYZE TABLE REPROCESS_TXNS               COMPUTE STATISTICS;
ANALYZE TABLE RUBROS                       COMPUTE STATISTICS;
ANALYZE TABLE SALDOS_CUENTAS               COMPUTE STATISTICS;
ANALYZE TABLE SELLOS                       COMPUTE STATISTICS;
ANALYZE TABLE TARJETAS                     COMPUTE STATISTICS;
ANALYZE TABLE TRANS_BATCH_ISSR             COMPUTE STATISTICS;
ANALYZE TABLE TRANSFER_TRANS               COMPUTE STATISTICS;
ANALYZE TABLE WFQ_INFO_ADICIONAL           COMPUTE STATISTICS;
ANALYZE TABLE WFQ_MENSAJES                 COMPUTE STATISTICS;
ANALYZE TABLE WFQ_HIST_ESTADOS             COMPUTE STATISTICS;
ANALYZE TABLE FECHAS_ESTADO_TARJETAS       COMPUTE STATISTICS;
ANALYZE TABLE TIPO_DE_CAMBIO               COMPUTE STATISTICS;
ANALYZE TABLE S_ENTIDAD_SERV               COMPUTE STATISTICS;






