--
-- RELATORIO PARA AVALIAR COMO OS INDICES FORAM UTILIZADOS
--

SELECT
   P.OBJECT_NAME NOME_OBJETO,
   P.OPTIONS     OPCAO,
   COUNT(1)      QTDE_VEZES_EXECUTADO
FROM
   DBA_HIST_SNAPSHOT  SN,
   DBA_HIST_SQL_PLAN   P,
   DBA_HIST_SQLSTAT    S,
   DBA_INDEXES         I
WHERE  P.OBJECT_OWNER  = 'SUPORTERJ'
AND    P.OPERATION LIKE '%INDEX%'
AND    P.SQL_ID        = S.SQL_ID
AND    SN.SNAP_ID      = S.SNAP_ID    
AND    TRUNC(SN.BEGIN_INTERVAL_TIME) BETWEEN TO_DATE('01012011','DDMMYYYY') AND TO_DATE('14022011','DDMMYYYY') 
AND    I.OWNER         = P.OBJECT_OWNER
AND    I.TABLE_NAME    = 'PROPOSTA'
AND    I.INDEX_NAME    = P.OBJECT_NAME 
GROUP BY
   P.OBJECT_NAME,
   P.OPTIONS
ORDER BY 1,2;


--
-- AVALIAR DOS INDICES QUE FORAM UTILIZADOS, QUANTAS VEZES FORAM UTILIZADOS POR DIA COM TOTALIDADOR ROLLUP
--

SELECT
   P.OBJECT_NAME NOME_OBJETO,
   TO_CHAR(SN.BEGIN_INTERVAL_TIME,'YYYY-MM-DD HH24') TIME,   
   P.OPTIONS     OPCAO,   
   COUNT(1)      QTDE_VEZES_EXECUTADO   
FROM
   DBA_HIST_SNAPSHOT  SN,
   DBA_HIST_SQL_PLAN   P,
   DBA_HIST_SQLSTAT    S,
   DBA_INDEXES         I
WHERE  P.OBJECT_OWNER  = 'SUPORTERJ'
AND    P.OPERATION LIKE '%INDEX%'
AND    P.SQL_ID        = S.SQL_ID
AND    SN.SNAP_ID      = S.SNAP_ID    
AND    TRUNC(SN.BEGIN_INTERVAL_TIME) BETWEEN TO_DATE('01012011','DDMMYYYY') AND TO_DATE('14022011','DDMMYYYY') 
AND    I.OWNER         = P.OBJECT_OWNER
AND    I.TABLE_NAME    = 'PROPOSTA'
AND    I.INDEX_NAME    = P.OBJECT_NAME
AND    P.OBJECT_NAME  <> 'PK_PROPOSTA' 
GROUP BY rollup(
   P.OBJECT_NAME,
   P.OPTIONS,
   TO_CHAR(SN.BEGIN_INTERVAL_TIME,'YYYY-MM-DD HH24'))
ORDER BY 1,2,3;


--
-- QUERY PARA VERIFICAR QUAL O SQL ESTA SENDO EXECUTADO PARA ESTE INDICE.
--
SELECT 
   P.OBJECT_NAME NOME_OBJETO,
   TO_CHAR(SN.BEGIN_INTERVAL_TIME,'YYYY-MM-DD') TIME,   
   P.OPTIONS     OPCAO,
   T.SQL_TEXT         INSTRUCAO_SQL   
FROM
   DBA_HIST_SNAPSHOT  SN,
   DBA_HIST_SQL_PLAN   P,
   DBA_HIST_SQLSTAT    S,
   DBA_INDEXES         I,
   DBA_HIST_SQLTEXT    T
WHERE  P.OBJECT_OWNER  = 'SUPORTERJ'
AND    P.OPERATION LIKE '%INDEX%'
AND    P.SQL_ID        = S.SQL_ID
AND    SN.SNAP_ID      = S.SNAP_ID    
AND    TRUNC(SN.BEGIN_INTERVAL_TIME) BETWEEN TO_DATE('01012011','DDMMYYYY') AND TO_DATE('14022011','DDMMYYYY') 
AND    I.OWNER         = P.OBJECT_OWNER
AND    I.TABLE_NAME    = 'PROPOSTA'
AND    I.INDEX_NAME    = P.OBJECT_NAME
AND    P.OBJECT_NAME  <> 'PK_PROPOSTA'
AND    P.SQL_ID        = T.SQL_ID 
ORDER BY 1,2,3;
